name: Notificacion de Carreras de Sillas

on:
  push:
    branches:
      - main

jobs:
  check-and-notify:
    runs-on: ubuntu-latest

    steps:
      # 1. Revisamos el codigo
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2. Validamos que el script.js exista y tenga las sillas definidas
      - name: Validar script de sillas
        run: |
          if grep -q "chair-0" script.js; then
            echo "Script validado: Las sillas están configuradas."
          else
            echo "Error: No se encontraron las sillas en script.js"
            exit 1
          fi

      # 3. Notificación de éxito
      - name: Notificar éxito a ntfy
        if: success()
        run: |
          curl -H "Title: ¡Pista Preparada!" \
               -H "Priority: high" \
               -H "Tags: racing_car,chair,white_check_mark" \
               -d "Todas las sillas están listas para correr. El deploy se ha realizado correctamente en el repositorio." \
               ntfy.sh/devops-itla

      # 4. Notificación de error
      - name: Notificar fallo a ntfy
        if: failure()
        run: |
          curl -H "Title: Error en el Boxes" \
               -H "Priority: urgent" \
               -H "Tags: x,warning" \
               -d "Hubo un fallo en el proceso. Las sillas no están listas para la carrera." \
               ntfy.sh/devops-itla